### ISSUE TITLE
Do you have a prebuilt installable release that installs on Ubuntu ?

### ISSUE THREAD

**Issue by johnburkey** [buttaface/swift-android-sdk#31]
Would like to try using your setup for droid, and am hoping for something similar to vgorloffs where we just execute swift build with a destination json and it generates 64bit droid .so’s.

(we like to have an AWS instance for builds- so would prefer Ubuntu install but are flexible)

**Comment by buttaface** [comment]
It would depend what you mean by "installable." My Android CI simply builds an SDK using the official release or snapshot compilers from swift.org, and then cross-compiles various Swift packages using the destination JSON in this repo. My README explains how you can do the same with [my prebuilt release SDKs](https://github.com/buttaface/swift-android-sdk/releases), after modifying a few config files. [My CI script gives you concrete examples](https://github.com/buttaface/swift-android-sdk/blob/main/.github/workflows/sdks.yml) of the same. If you have any questions about translating any of that to your process, let me know.

**Comment by johnburkey** [comment]
Does your CI put its output anywhere, like something I could wget and use with a -destination json, or is the way to use it to figure out your scripts and try to emulate what you are doing?

**Comment by buttaface** [comment]
Why do you want the output of my CI, which mostly consists of [x86_64 build artifacts and test runners that it can then run in the Android x86_64 emulator](https://github.com/buttaface/swift-android-sdk/blob/main/.github/workflows/sdks.yml#L336)?

The best way to set this up is to follow [the short instructions in my README](https://github.com/buttaface/swift-android-sdk#readme), which show you how use my prebuilt SDKs alongside the official Android NDK and official Swift compiler from swift.org, requiring only a little text configuration to change some paths for your build environment the first time you set it up. After that, you can script that configuration, as I do on my CI, for the couple times a year when you update the compiler or NDK.

I realize this is not as turnkey as just getting a cross-compilation toolchain that works out of the box, but it isn't much, and I plan to automate these last few steps too.

**Comment by johnburkey** [comment]
Oh, I thought your CI made a toolchain I could use on ubuntu to generate droid artifacts.

**Comment by buttaface** [comment]
No, I never build the Swift compiler for these cross-compilation SDKs, using the official toolchain builds from swift.org instead. The Android SDKs I build consist of a cross-compiled standard library, libdispatch, libFoundation, and libXCTest, which are enough to cross-compile and test Swift packages for Android with the official toolchain builds.

**Comment by johnburkey** [comment]
Gorloff builds a toolchain, so I assumed you did too.

I remember that you build natively on droid, right?  Have you cross compiled from Linux recently, and seen a concurrency using piece of code compile & run on droid?
I ask because i've heard that lib dispatch may need some work on platforms other than Apple to support the new concurrency stuff.

- John

**Comment by buttaface** [comment]
The terminology Swift uses is that the toolchain has the compiler, stdlib, package manager, and everything else, while an SDK only contains the libc headers and libc library for a platform alongside a handful of Swift libraries, ie the standard library, the Swift "corelibs" of libdispatch, Foundation, and XCTest (only for testing), and now the Swift concurrency runtime.

The prebuilt Android SDKs I build provide the latter, while the Android NDK provides the Bionic libc, so together they constitute a Swift Android SDK, that would in theory let you cross-compile for Android from any other Swift platform toolchain.

While this Android cross-compilation didn't work with the official Swift Xcode toolchain last time Vlad tried it, #1, it should work with the Homebrew bottle of Swift on macOS, which is now up to date. 

> I remember that you build natively on droid, right?

I do that separately in other repos, everything in this repo has to do with cross-compilation to Android from non-Android platforms. These Swift 5.5.2 cross-compilation SDKs were built on Fedora Core 35, and you can follow my README instructions to build the SDKs yourself too. 

> Have you cross compiled from Linux recently, and seen a concurrency using piece of code compile & run on droid?

Yes, [I wrote you on the forum about it last weekend](https://forums.swift.org/t/swift-on-android-could-use-help-from-swift-linux-people/54498/3), you can try it for yourself by following what I did there.

> I ask because i've heard that lib dispatch may need some work on platforms other than Apple to support the new concurrency stuff.

Maybe, but since Apple has done all the work for it to work on linux, presumably for their Swift Server efforts, it all just seems to work on Android too, at least all the compiler validation suite tests related to concurrency pass on Android.

**Comment by buttaface** [comment]
Closing since I answered all your questions, feel free to ask more though.
