### ISSUE TITLE
5.6 support ?

### ISSUE THREAD

**Issue by SimpleApp** [buttaface/swift-android-sdk#32]
I'm running on an apple silicon, and swift only released its toolchain for "trunk" on that architecture for ubuntu. Which means 5.6.
Is 5.6 supported by your SDK ? 

If not, would i be able to use the swift 5.5.2 build that's installed on my Mac OS, or is it possible to build for android only from a linux distribution ?

**Comment by buttaface** [comment]
No, I only release builds of 5.5 for now. I think you could use [the Swift 5.5.2 build from Homebrew](https://formulae.brew.sh/formula/swift) with my SDK without a problem, but I haven't tried it to confirm.

**Comment by buttaface** [comment]
The main issue that might come up with building on AArch64 is that the Android NDK is currently only available for x86_64, though they're working on it, android/ndk#1299. Since the Swift setup described here uses the NDK clang and lld to compile C/C++ code and link everything, you'd need to run those NDK tools on macOS in x86_64 emulation mode.

Alternately, you could [change the `tools-directory`](https://github.com/buttaface/swift-android-sdk/blob/3cdf2ebd23f89907deb593f292d8e42e8176bf4a/android-aarch64.json#L11) to a Swift toolchain that normally includes those LLVM tools, whether on mac or linux, and that should work too.

**Comment by buttaface** [comment]
Feel free to ask any more questions, or let me know how it worked out for you.
