### ISSUE TITLE
"dlopen failed: empty/missing DT_HASH/DT_GNU_HASH" crash in runtime

### ISSUE THREAD

**Issue by neekeetab** [buttaface/swift-android-sdk#59]
Hey! Thanks for doing this! 

So I built a swift lib by using your guide, but I'm getting "dlopen failed: empty/missing DT_HASH/DT_GNU_HASH" on android just when the lib is loaded to the memory. Did you encounter smth similar by chance?

Build command: 
`
/toolchain/swift-5.6-RELEASE-ubuntu20.04/usr/bin/swift build -v -c release --destination /toolchain/swift-android-sdk/android-aarch64.json -Xlinker -rpath -Xlinker /toolchain/swift-5.6-android-aarch64-24-sdk/usr/lib/swift/android
`

I found this question with a possible fix for c++. Maybe there's a swift compiler setting like this? Couldn't find one.
https://stackoverflow.com/questions/28638809/android-ndk-unsatisfiedlinkerror-dlopen-failed-empty-missing-dt-hash

**Comment by neekeetab** [comment]
Nevermind, we had to remove all occurances of lib dispatch and lib concurrency (along with corresponding .swiftmodule files) and it worked

**Comment by buttaface** [comment]
Hey @neekeetab, I didn't even see this issue when you opened it, because you closed it so fast. You may want to try [this recent solution for libdispatch on Android instead (see the next comment too)](https://github.com/buttaface/swift-android-sdk/issues/67#issuecomment-1227460068), otherwise you will not be able to use structured concurrency.
