### ISSUE TITLE
Could you make a new release for Swift 5.7.1 ?

### ISSUE THREAD

**Issue by johnburkey** [buttaface/swift-android-sdk#80]
I can't find an Apple toolchain compatible with your latest release- they've already hidden it, so I get these:   

error: module compiled with Swift 5.7 cannot be imported by the Swift 5.7.1 compiler:

**Comment by johnburkey** [comment]
still looking for a 5.7 toolchain in the meantime.

**Comment by johnburkey** [comment]
found 5.7

**Comment by johnburkey** [comment]
error: link command failed with exit code 1 (use -v to see invocation)
ld.lld: error: unknown -z value: nostart-stop-gc

**Comment by johnburkey** [comment]
I think I might getting that setting from the NDK, going to try switching NDKs

**Comment by buttaface** [comment]
I'm going to see if the official 5.7.1 compiler for linux works with my 5.7 SDK. If it does, I won't be releasing a new SDK, as before.

The macOS compiler has always been more particular about the version, I suggest you build the 5.7.1 SDK yourself using the instructions in my doc. It's only a handful of steps that's easily scripted, as you can see in my CI script that rebuilds the SDK for every trunk snapshot.

> error: link command failed with exit code 1 (use -v to see invocation)
ld.lld: error: unknown -z value: nostart-stop-gc

That indicates you are using an old pre-13 lld to link: make sure you're using NDK 25 as NDK 23 and older will no longer work with 5.7 and up.

**Comment by KittyMac** [comment]
> I'm going to see if the official 5.7.1 compiler for linux works with my 5.7 SDK. If it does, I won't be releasing a new SDK, as before.

I tried using the official 5.7.1 compiler against the 5.7 SDK.  It does not appear to work for me:

```
#0 1.726 <unknown>:0: error: module compiled with Swift 5.7 cannot be imported by the Swift 5.7.1 compiler: /root/swift-5.7-android-x86_64-24-sdk/usr/lib/swift/android/Swift.swiftmodule/x86_64-unknown-linux-android.swiftmodule
```

I would love a 5.7.1 SDK release!

**Comment by buttaface** [comment]
I was generating these releases manually, by using the scripts and instructions from my doc, but I've now modified my CI to upload the SDKs it generates, 64bcef4, so [you can just get them from there, including the trunk snapshot SDKs](https://github.com/buttaface/swift-android-sdk/actions/runs/3443808789). I will trim them a bit- especially x86_64 because it also includes the test runners that are tested on the CI- and upload them to the releases page later today, but you can always get them yourselves from the CI from now on.
